config/routes.rb
Rails.application.routes.draw do

  resources :hits
  resources :players



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hit.rb
class Hit < ApplicationRecord
  belongs_to :player
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :hits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hits_controller.rb
class HitsController < ApplicationController

  before_action :set_hit, only: [:show, :edit, :update]

  def index
    @hits = Hit.all
  end


  def show
    last_id = Hit.last.id
    if @hit.id > 1
      @previous_hit = Hit.find(@hit.id - 1)
    end
    if @hit.id < last_id
      @next_hit = Hit.find(@hit.id + 1)
    end

  end


  def new
    @hit = Hit.new
  end


  def create
    @hit = Hit.new(hit_params)

    @hit.player_id = @hit.digit_left.to_i*10 + @hit.digit_right.to_i


    if @hit.save
      flash[:success] = "Hit was created successfully"
      redirect_to hit_path(@hit)
    else
      render 'new'
    end
  end


  def edit

  end


  def update

    @hit.player_id = @hit.digit_left.to_i*10 + @hit.digit_right.to_i


    if @hit.update(hit_params)
      flash[:success] = "Hit was updated successfully"

          @hit.player_id = @hit.digit_left.to_i*10 + @hit.digit_right.to_i
          @hit.update(hit_params)


      redirect_to hit_path(@hit)
    else
      render 'edit'
    end
  end


  def destroy
    @hit = Hit.find(params[:id]).destroy
    flash[:success] = "Hit deleted successfully"
    redirect_to hit_path
  end



private

  def set_hit
    @hit = Hit.find(params[:id])    
  end

  def hit_params
    params.require(:hit).permit(:comments, :head, :chest, :back, :digit_left, :digit_right, :slurring)    
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_action :set_player, only: [:show, :edit, :update]

  def show
    hits = Hit.all
    @individual_hits = @player.hits
    
  end



private

  def set_player
    @player = Player.find(params[:id])    
  end

  def player_params
    params.require(:player).permit(:name)    
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hits/_form.html.erb
<%= render 'shared/errors', obj: @hit %>

<div class="row">
    
    <%= form_for(@hit, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
        <div class="col-sm-2">
            <div class="btn-group" data-toggle="buttons">

              <% (0..9).each do |i| %>
                 
                  <%= f.radio_button :digit_left, i %>
                  <span class="digitlabels"><%= i %></span>
                  <br><br>
              <% end %>

            </div>
        </div>

        <div class="col-sm-2">
            <div class="btn-group" data-toggle="buttons">
              <% (0..9).each do |i| %>
                  <%= f.radio_button :digit_right, i %>
                  <span class="digitlabels"><%= i %></span>
                  <br><br>
              <% end %>

            </div>
        </div>


            <div class="col-sm-3">

                  <%= f.check_box :head %> <span class="bodylabels">Head</span>
                  <br><br><br>
                  <%= f.check_box :chest %> <span class="bodylabels">Chest</span>
                  <br><br><br>
                  <%= f.check_box :back %> <span class="bodylabels">Back</span>

                <br>
            </div>


        <div class="control-label col-sm-1">
          <%= f.label :comments %>
        </div>
        <div class="col-sm-3">
          <%= f.text_area :comments, rows: 2, class: "form-control", placeholder: "any comments" %>


      <div class="col-sm-1">
        <br><br><br><br><br><br><br>
        <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
      </div>

      </div>



    <br><br>


</div>


        <div class="col-sm-6 col-sm-offset-2">
            <div class="btn-group" data-toggle="buttons">
              <% (1..7).each do |i| %>
                  <%= f.radio_button :slurring, i %> 

              <% end %>
              <br>
              <span class="afterlabels">1 2 3 4 5 6 7   - SLURRING</span>


            </div>
        </div>



      <% end %>    


</div>

app/views/hits/edit.html.erb
<%= render 'shared/page_title', title: "Edit an existing Hit" %>

<%= render 'form' %>

app/views/hits/new.html.erb
<%= render 'shared/page_title', title: "Create a new hit" %>

<%= render 'form' %>

app/views/hits/show.html.erb
<%= render 'shared/page_title', title: "Hit Summary" %>



<div class="col-sm-1">
  

<br><br><br>
<br><br><br>


    <% if @previous_hit.blank? %>

    <% else %>
      <%= link_to "<-- Previous Hit", hit_path(@previous_hit), class: "btn btn-xs btn-warning" %>
    <% end %>


</div>

<div class="col-sm-3 col-sm-offset-2">


  <h1> <%= link_to "Player #"+@hit.player_id.to_s, player_path(@hit.player_id) %>   </h1>



  <h2>Hit to</h2>


  <ul>
    <li><h3>Head:
      <%= @hit.head %>  </h3></li>
    <li><h3>Chest: <%= @hit.chest %> </h3></li>
    <li><h3>Back: <%= @hit.back %> </h3></li>
  </ul>

  <br>


  <h3>SLURRING: <%= @hit.slurring %></h3>

    <%= simple_format(@hit.comments) %>



  <%= @hit.created_at.strftime("%F") %> @ 
  <%= @hit.created_at.strftime("%H:%M") %>

  <br><br><br>

      <%= link_to "Edit Hit", edit_hit_path(@hit), class: "btn btn-xs btn-info" %>


</div>


<div class="col-sm-1">
  

<br><br><br>
<br><br><br>


    <% if @next_hit.blank? %>
      <%= link_to "New Hit", new_hit_path, class: "btn btn-xs btn-danger" %>

    <% else %>
      <%= link_to "Next Hit -->", hit_path(@next_hit), class: "btn btn-xs btn-warning" %>
      <br><br><br>

      <%= link_to "New Hit", new_hit_path, class: "btn btn-xs btn-danger" %>

  
  <% end %>




</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <em> Serge Lafontaine</em>
  </small>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215</a>
        <%= msg %>
      </div>
    <% end %>
    
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ProjectCharlie", new_hit_path, class: "navbar-brand", id: "logo" %>


    </div>

  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Charlie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>

    <div class="container">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/players/show.html.erb
<%= render 'shared/page_title', title: "Player Summary" %>



<div class="col-sm-6 col-sm-offset-2">

  <h1><%= @player.name %>  #<%= @player.id %></h1>








<table class="table table-striped table-responsive">
  <thead>
    <tr>
      <th>Date</th>
      <th>Head</th>
      <th>Chest</th>
      <th>Back</th>
      <th>SLURRING</th>
      <th>TOTAL</th>
      <th></th>

    </tr>
  </thead>

  <tbody>
    <% @individual_hits.each do |hit| %>
      <tr>

        
        <td><%= hit.created_at.strftime("%F")  %></td>
        <td><%= hit.head  %></td>
        <td><%= hit.chest  %></td>
        <td><%= hit.back  %></td>
        <td><%= hit.slurring  %></td>
        <td><%= hit.slurring.to_i+hit.back.to_i+hit.chest.to_i+hit.head.to_i  %></td>
        <td><%= link_to "EDIT", edit_hit_path(hit)  %></td>

      </tr>
    <% end %>
  </tbody>
</table>

 </div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this <%= obj.class %> from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<h1 align="center"> <%= title %> </h1>
<hr />